for file in ~/.dotfiles/bash/{path,bash_prompt,exports,exports_private,aliases,functions,extra,locale,completion,docker}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

if [ -d "$HOME/Projects" ]; then
  cd ~/Projects
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/acid/Projects/google-cloud-sdk/path.bash.inc' ]; then source '/Users/acid/Projects/google-cloud-sdk/path.bash.inc'; fi

logs() {
    AWS_REGION=us-west-2 AWS_DEFAULT_PROFILE=inf awslogs get $1 ALL --no-group --no-stream --start='20m ago' --watch | jq .log
}

# The next line enables shell command completion for gcloud.
if [ -f '/Users/acid/Projects/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/acid/Projects/google-cloud-sdk/completion.bash.inc'; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export JAVA_HOME=`/usr/libexec/java_home -v '1.8*'`
