for file in ~/.dotfiles/bash/{path,bash_prompt,exports,exports_private,aliases,functions,extra,locale,completion,docker}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

if [ -d "$HOME/Projects" ]; then
  cd ~/Projects
fi
